### ISSUE TITLE
separate does not function as expected

### ISSUE THREAD

**Issue by AlexChesser** [TykTechnologies/tyk-operator#591]
I am using the following command line to export api definitions from an instance with multiple APIs under the same OWNER: `./tyk-operator -separate -apidef /output/apidef.yaml -policy /output/policy.yaml -category \${API_EXPORT_CATEGORY}`   (assume category has been set as an environment variable)

## Expected Behavior

multiple API CRD files generated 

## Current Behavior

no files generated at all 

## Possible Solution

unknown.

`./tyk-operator -apidef /output/apidef.yaml -policy /output/policy.yaml -category \${API_EXPORT_CATEGORY}`   will generate 2 files (policy and apidef)

`./tyk-operator -apidef /output/apidef.yaml -policy /output/policy.yaml -category \${API_EXPORT_CATEGORY}` generates nothing at all

## Steps to Reproduce

1. create 2 apis in a tyk cloud instance
2. run the command found in https://github.com/alexchesser/tyk-operator-wrapper
3. `:sadface:`

## Logs/Errors

unfortunately the output looks the same for the unsuccessful as well as the successful run even if I include zap-log-level of debug

```
alexanderchesser@alexanderchesser tyk-config % ./docker-export-configs.sh                         

exporting apis and policies for category owner-foo
RUNNING COMMAND: ./tyk-operator --separate --category owner-foo --policy /output/policy.yaml --apidef /output/apidef.yaml
{"level":"info","ts":1679516720.9566388,"logger":"snapshot.ApiDefinition","msg":"Call","Method":"GET","URL":"https://my-instance-adm.aws-use1.cloud-ara.tyk.io/api/apis","Status":200}
{"level":"info","ts":1679516721.0670464,"logger":"snapshot.ApiDefinition","msg":"Call","Method":"GET","URL":"https://my-instance-adm.aws-use1.cloud-ara.tyk.io/api/portal/policies?p=-2","Status":200}
Looking for ApiDefinitions in #owner-foo category.
alexanderchesser@alexanderchesser tyk-config %
```

## Context

I'm trying to export 1 file per api so that when they are checked in to CICD they are more easily reviewed

## Your Environment

this is running within the docker container `alexchesser/tyk-operator-wrapper` in docker hub.
the tyk operator version this is failing with was compiled today using 

```
FROM golang:1.17.13 as builder
WORKDIR /build
RUN git clone --depth 1 https://github.com/TykTechnologies/tyk-operator.git .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go
```

**Comment by buraksekili** [comment]
hi @AlexChesser,

Which version of Tyk Operator are you using? I checked your [Dockerfile](https://github.com/AlexChesser/tyk-operator-wrapper/blob/main/Dockerfile) and seems like you are building the image after fetching it from GitHub.

I've tested the scenario with `v0.13.0` of Tyk Operator and it is working fine for me - I'll put output details at the end.

We are actively working on this tool to make it more user-friendly. We've merged recent improvements on master which are not been officially released yet. In brief, we'll allow users to use `docker` image of Tyk Operator instead of suggesting users to build the binary locally. More details can be found here: https://github.com/TykTechnologies/tyk-operator/blob/master/pkg/snapshot/README.md
So, in order to do that we changed the output directory of the tool. Snapshot will export resources to `/dist` folder within Operator container. If you mount your local volume to `dist` folder of the container, you can access generated files. If you still want to run Operator locally, again Operator creates a folder `/dist` and will save generated files in this directory.

So, you may want to update your Dockerfile to make it compatible with recent changes. As I said, you can find more details in the [snapshot docs.](https://github.com/TykTechnologies/tyk-operator/blob/master/pkg/snapshot/README.md)


The output of v0.13.0
```bash
tyk-operator git:(master) $ git checkout tags/v0.13.0
Note: switching to 'tags/v0.13.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 4710aa5c version to: v0.13.0
tyk-operator git:(4710aa5c) $ go build && TYK_MODE=pro TYK_URL=${TYK_URL} TYK_ORG=${TYK_ORG} TYK_AUTH=${TYK_AUTH} ./tyk-operator --separate -apidef apidef.yaml -policy policy.yaml -category owner-foo
{"level":"info","ts":1679550708.257833,"logger":"setup","msg":"unable to get WatchNamespace, the manager will watch and manage resources in all Namespaces"}
{"level":"info","ts":1679550708.746718,"logger":"snapshot.ApiDefinition","msg":"Call","Method":"GET","URL":"${TYK_URL}/api/apis","Status":200}
{"level":"info","ts":1679550708.8362281,"logger":"snapshot.ApiDefinition","msg":"Call","Method":"GET","URL":"${TYK_URL}/api/portal/policies?p=-2","Status":200}
tyk-operator git:(4710aa5c*) $ gss
HEAD detached at v0.13.0
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	samplenamepsapce-sample-name.yaml
	samplenamepsapce-sample-name2.yaml

nothing added to commit but untracked files present (use "git add" to track)
tyk-operator git:(4710aa5c*) $ cat samplenamepsapce-sample-name.yaml | yq .metadata
creationTimestamp: null
name: sample-name
namespac
```

**Comment by AlexChesser** [comment]
let me try with `0.13.0` and I'll follow up.

**Comment by AlexChesser** [comment]
Good news, bad news, and more bad news.

**The Good News**: 

after updating my [dockerfile](https://github.com/AlexChesser/tyk-operator-wrapper/blob/main/Dockerfile) to pull from the image v0.13.0 the `SEPARATE` flag does appear to correctly support the creation of multiple files as expected.  🥳 🎉 

**The Bad News**: 

it looks like the `-category` flag is not being respected.  When I run the command `/workspace/tyk-operator -separate -category \${API_EXPORT_CATEGORY}`  having only two apis in the "owner-foo" category  I get ALL apis exported instead of just the ones my team owns.

**The More Bad News**: 

If any one of the APIs  one of the APIs on the entire dashboard is missing the `k8sName/Namespace` Config data it looks like the export will fail even if the api without config data does not have the category I'm trying to export.  This winds up being really problematic for making this function as expected in a multi-team environment - since any one team could take down exports for the entire org!  😳  yikes

```
RUNNING COMMAND: /workspace/tyk-operator -separate -category owner-clockwork
{"level":"info","ts":1679582240.1123803,"logger":"setup","msg":"unable to get WatchNamespace, the manager will watch and manage resources in all Namespaces"}
I0323 14:37:21.621048      10 request.go:668] Waited for 1.010128708s due to client-side throttling, not priority and fairness, request: GET:https://BF32171E856030CC2B5EE93E69D50D3A.gr7.us-east-1.eks.amazonaws.com/apis/coordination.k8s.io/v1?timeout=32s
{"level":"info","ts":1679582242.226084,"logger":"snapshot.ApiDefinition","msg":"Call","Method":"GET","URL":"https://aesthetic-asphalt-adm.aws-use1.cloud-ara.tyk.io/api/apis","Status":200}
{"level":"info","ts":1679582242.3631074,"logger":"snapshot.ApiDefinition","msg":"Call","Method":"GET","URL":"https://aesthetic-asphalt-adm.aws-use1.cloud-ara.tyk.io/api/portal/policies?p=-2","Status":200}
WARNING: failed to parse API b5ef85e7178f452c70b055a35135f6f0 due to malformed ConfigData, err: failed to parse 'k8sName' field in ConfigData
{"level":"error","ts":1679582242.3979282,"logger":"snapshot.ApiDefinition","msg":"failed to create snapshot file","error":"failed to parse 'k8sName' field in ConfigData","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
```

**Comment by AlexChesser** [comment]
OK - I took a look at #565 and we're back to almost exclusively good news


updating my dockerfile to go back to building itself and merging 565 makes the operator work as expected on both issues.
```
FROM golang:1.17.13 as builder
WORKDIR /build
RUN git config --global user.email "tyk-operator-wrapper-container@example.com"
RUN git config --global user.name "Tyk Container"
RUN git clone https://github.com/TykTechnologies/tyk-operator.git .
RUN git merge origin/snapshot-UX-improvement
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go
```

**Comment by AlexChesser** [comment]
Actually, I've just noticed that policies are still getting exported even if their category is not set to the one I am exporting.

**Comment by zalbiraw** [comment]
Hi @AlexChesser so filtering by category is not supported at the policy level because policies do not have categories. I am assuming what you are looking for is filtering policies by the categories their APIs are associated with. This will have to be a feature request and is probably something we will want to do as we enhance the UX of the snapshot. I will go ahead and close this issue for now as I created a [this](https://github.com/TykTechnologies/tyk-operator/issues/592) feature request.
